version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: 
      - ./datasources/mysql/database:/var/lib/mysql
  bookstore_users-api:
    image: bookstore_users-api
    ports:
      - "8080:8080"
    depends_on: 
        - mysql
    restart: always