name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...
    
    - name: Build and push to gcr
      uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
      with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: asia.gcr.io
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          image_name: bookstore_users-api
      env:
          MYSQL_USERS_USERNAME: ${{ secrets.MYSQL_USERS_USERNAME }}
          MYSQL_USERS_PASSWORD: ${{ secrets.MYSQL_USERS_PASSWORD }}
          MYSQL_USERS_HOST: ${{ secrets.MYSQL_USERS_HOST }}
          MYSQL_USERS_SCHEMA: ${{ secrets.MYSQL_USERS_SCHEMA }}
      
